### ISSUE TITLE
Research: New API endpoint for Linked Candidate/Committee information from FEC

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#374]
***Research Task:*** Determine how we can pull linked Candidate/Committee information from FEC into FECfile Online to populate contact information in secondary/tertiary contacts within a transaction (and potentially the primary), as well as Contact Management in the future.

***Example:***

  Contribution to Candidate (specification in progress [here]([https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=102820213](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=102820213))) calls for a PAYEE entity (COM), that then pulls the same info into the Beneficiary Committee ID/Name fields. Using that committee information, we should be able to pull in the linked candidate information into the Beneficiary Candidate fields.

Things to consider:

*   ***This could eventually be in contact management, and is not just for Schedule B***
*   The primary ENTITY of a transaction could be an IND or ORG type, and then the user needs to enter the Beneficiary Candidate/Committee.
*   FEC will want any new contacts pulled into a transaction to be saved as new contacts to the Contact Management database for the committee account.
*   Users will still have the ability to edit the fields if they are pulled in
*   _Potentially_ have lookup functionality for the candidate or committee both, so that we can accommodate the user knowing one but not the other (need further clarification from FEC on this)

***Tech Notes***

  The additional contact records should be able to be added to a transaction by adding additional foreign keys from the sub-transaction table where it is needed to the contacts table. A secondary thing to consider is to review the contact lookup angular component to see what work, if any, needs to be made to it so that a single transaction entry form can support multiple lookup components. Additionally, a committee can have a association with a candidate contact, so investigate providing a link between contact records for this purpose.

### QA Notes ###
- None for this ticket, this is research only. Functionality will be tested in future tickets.

### DEV Notes ###
null

### Design ###
null

 See full ticket and images here: [FECFILE-291](https://fecgov.atlassian.net/browse/FECFILE-291)

**Comment by Elaine-Krauss-TCG** [comment]
When retrieving a committee from the [FEC API](https://api.open.fec.gov/developers/#/committee/get_committee__committee_id__), an array of Candidate ID's is included in the data returned.  These ID's can then be used to query the [candidate endpoint](https://api.open.fec.gov/developers/#/candidate/get_candidate__candidate_id__) to get the full data for the candidates in question.  This data can then be sent to the front-end where it can be patched into the relevant fields.

The API's contact model should be updated to support a many-to-many relationship (soft-confirmed with Aurelia) between candidates and committees.  When a contact is serialized, it should include information from related contacts (the candidate in this case) so that the front-end can populate fields on the Contribution to Candidate and similar receipts.

On the front-end, a new parameter should be added to the transaction model, defaulting to None, that controls whether or not the secondary contact fields will be shown and what entity type they would correspond to.  The contact-form component will need to be updated accordingly.

When a user is working on a receipt with a secondary contact such as the Contribution to Candidate, and when the user makes use of the contact-lookup feature, if a contact is retrieved from the database, the first related contact should be used to populate the secondary contact's fields.  If a contact is retrieved from the FEC, however, then any related contacts (such as those listed in a committee's candidate_ids field) should be retrieved and sent along with the searched-for contact to the front-end.

**Comment by mjtravers** [comment]
Ticket meets requirement of describing how to pull candidates associated with a committee and how to pull committees associated with a candidate from the FEC API. Passes content review. Sending on to QA.

**Comment by WiseQA** [comment]
QA verified with DEV the research denoted above is adequate for New API endpoint(s).  

Future tickets will be created for functionality.

Moved to Stage Ready.
