### ISSUE TITLE
SPIKE - Transactions performance issues

### ISSUE THREAD

**Issue by WiseQA** [fecgov/fecfile-web-api#633]
Transactions performance issues noticed during testing for Loans and Debts.

1.  Loading of transactions for a report.   Loans and Debts lagging load time.

<img width="1186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmR6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38382f0c382a5b2ddbab39230b0241d59155b85a/image.png" alt="image.png" />

_________________________________________________________________________________________________________________________________
2.  Transactions slow to load under Loans and Debts (e.g., Loan Received from Individual) (Counted to 12 before loading)

__________________________________________________________________________________________________________________________________
3.  +Save & add loan guarantor - lags in loading the Guarantors page

<img width="1157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnB6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e131cbb547e632a41b525964e000cef7c503b5a6/image.png" alt="image.png" />

__________________________________________________________________________________________________________________________________
4.  Select "Save" after entering a new Guarantor lags taking you back to transactions page

<img width="1228" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjF6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--376dd1d9944c21c5c54582a9b84ff3f543e32801/image.png" alt="image.png" />

5.  When pulling up transactions with Guarantor's (e.g., Loan Received from Individual) the Guarantors list is not displayed upon opening of transaction.  

<img width="1198" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJ6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1fab77bbff49b2a1422483560d1a52e21228dc7/image.png" alt="image.png" />

6.  Guarantor's then populate after a few minutes

<img width="1194" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJ6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baa52912f1ee3f0ecc379e9f672e4fa9c2e58c78/image.png" alt="image.png" />

@mjtravers per our conversation above is one example of a Loans and Debts performance issues noticed during testing.

### DEV Notes ### 
Ideally one could track down the performance issues locally so give that a try first. First step is to install a profiling tool.
Here's one being looked into for monitoring in cloud.gov: https://github.com/Opus10/django-pgactivity
Here's another one to look at: https://github.com/jazzband/django-silk

**Comment by WiseQA** [comment]
During testing of Sprint 35 tickets it was also noticed the "Save" button once selected is lagging to take you back to Manage reports page.   Just and FYI to everyone - thanks

**Comment by toddlees** [comment]
Performance monitoring using django silk (https://github.com/jazzband/django-silk).  Found two things to be impacting performance of saves and gets.  
1) the runtime of core query to retrieve transactions, most especially the subqueries in the query.  To test it's impact, I removed the complexity (and obviously the correct functionality) of the query.  The request times reduced from ~6000ms to ~300ms
2) the number of subsequent queries being run on a given request due to logic and serialization after the initial data retrieval.  To test it's impact, I removed the complexity (and obviously the correct functionality) of the subsequent logic and serialization.  The request times reduced from ~6000ms to ~1200ms.

This told me that solving the query complexity would make a bigger impact on the overall request time.

To improve the query, I used window functions to calculate aggregates rather than subqueries.  This improved the performance but we lost the ability to filter out other committees' data due to Django's query api design.  To keep the performance boosts from using the window functions we made db views that use the window functions, and then write queries in the django query api that run on the new views.

Finding this design, I recommend we refactor our transaction viewset on the api so that queries are run against a view that uses window functions to calculate running totals.  The create and update calls will still need to hit the underlying table

**Comment by WiseQA** [comment]
Per DEV this ticket is a spike so there is no code or UI or tests to review by QA review.   The only thing is to look at the write up Todd did in the ticket comments describing his findings. The code part of the work is being done in ticket #656

No QA Review Required.   Moved to Stage Ready.
