### ISSUE TITLE
Fix database role errors in CircleCI database startup

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#66]
Some roles are missing in the database setup that are making the fecfile database import fail in CircleCI on web-api.

The fix is to add the roles import sql script to the CircleCI config.py job in the step: name: Load test database fixure

Here is a CircleCI job with the fail messages:
https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/188/workflows/78f9e1e1-b1ec-437b-b7ee-2b0bc3ddeb05/jobs/479

See Matt for SQL file with create role statements

##QA##
To verify no errors are being thrown when spinning up the test database, look at the output of the "Container cimg/postgre:12.8" section of the CircleCI [report page here](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/460/workflows/2b095a6f-d9a9-4875-83bf-81ede8f75a79/jobs/1283)

**Comment by Elaine-Krauss-TCG** [comment]
Following a swap in the database used by CircleCI, no more errors are present in the "Container" step of CircleCI's [test](https://app.circleci.com/pipelines/github/fecgov/fecfile-web-api/456/workflows/792224aa-c2e2-4fcb-8ac1-3725071a7008/jobs/1270) stage.

The "Container" step is still passing with a grey dash instead of the desired green checkmark, but comments in discussion threads have suggested that [this](https://discuss.circleci.com/t/build-was-canceled-with-docker/42447) and [similar behaviors](https://discuss.circleci.com/t/build-was-cancelled-in-database-containers/34411)  are [intended](https://discuss.circleci.com/t/postgresql-always-reports-job-was-canceled/29208).

After digging through the CircleCI documentation for a bit, I have seen no sign to suggest that there is a way to change this.

**Comment by mjtravers** [comment]
Passes code review. Sending to QA.

**Comment by WiseQA** [comment]
QA verified no errors displayed in the output of "Container cimg/postgre:12.8"t  see below screenshot:
![image.png](https://images.zenhubusercontent.com/61ba01e428a658b4eb0ca758/fb0a9a41-8c0b-4aba-99e9-af2edda49a09)

QA review completed.  Moved to Stage Ready.
