### ISSUE TITLE
SPIKE - Investigate cloud.gov zero-downtime process for Django migrations

### ISSUE THREAD

**Issue by mjtravers** [fecgov/fecfile-web-api#680]
In order, to achieve zero-downtime deployments, we need to understand how the rolling deployment updates affect the changing api versions and database changes.

For this ticket, do NOT think about solutions. This ticket is just to understand how the rolling deployment works on cloud.gov and it's affects on database and Django update timing. Once we understand how it works and what the problems are, we can then consider solutions in a future ticket that will be informed by this ticket's findings.

Things to consider:

- How are code deploys across instances timed with the database changes?
- Are api instances deployed one-by-one or in batches?
- Is incoming network traffic steered to the updated instances or limited to target instances in any way?
- How can we synchronize the front-end deployment with the api deployment so that the updated code is deployed as the api and database updates are deployed.... and rolled backed or terminated
- Look into options for testing with 5 or more instances withing the confines of our budget limitations

https://github.com/fecgov/fecfile-web-app/issues/40#issuecomment-1011301912
https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#limitations
https://github.com/fecgov/demo-apps

**Comment by dheitzer** [comment]
A few items from the [Limitations section](https://docs.cloudfoundry.org/devguide/deploy-apps/rolling-deploy.html#limitations) that may be applicable here:

`Multiple app versions - During a deployment, Cloud Foundry serves both the old and new version of your app at the same route. This can lead to user issues if you push backwards-incompatible API changes.`

`Database migrations	Deployments do not handle database migrations. Migrating an app database when the existing app is not compatible with the migration can result in downtime.`

`Non-web processes	Rolling deployments only run web processes through the rolling update sequence described earlier. The commands restart worker and other non-web processes in bulk after updating all web processes.`

It seems that based on these limitations, we will still incur some downtime even with rolling deploys in certain scenarios.

**Comment by dheitzer** [comment]
More answers:

How are code deploys across instances timed with the database changes?
`There is no coordination.  New instances are deployed one at a time and old instances are removed in the same manner until there are all new instances `
Are api instances deployed one-by-one or in batches?
`one-by-one`
Is incoming network traffic steered to the updated instances or limited to target instances in any way?
`The new instances share the same route as the old instances during the deploy, so there is no special routing or limiting`
How can we synchronize the front-end deployment with the api deployment so that the updated code is deployed as the api and database updates are deployed.... and rolled backed or terminated
`I could not find any support for doing this automatically, however it seems that manual [blue-green deploys](https://docs.cloudfoundry.org/devguide/deploy-apps/blue-green.html) would be in order to support this.  `
Look into options for testing with 5 or more instances withing the confines of our budget limitations

**Comment by dheitzer** [comment]
One question that I cannot seem to find an answer to is whether CF rolling deployments wait for each new instance to enter `FINALIZED	DEPLOYED` state before deploying the next instances.  If it does _not_ wait, we could theoretically have multiple instances running migrations simultaneously which wouldn't be good.  I think we will need to test for this if we use the rolling strategy.

**Comment by mjtravers** [comment]
No code to review. Findings above. Sending to QA.

**Comment by WiseQA** [comment]
No QA review needed on this SPIKE ticket.

Moved to Stage Ready.
