### ISSUE TITLE
Export data from ZenHub

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-api#773]
### Business Reason ### 

Given ZenHub will no longer be available to us as of March 31, we will need to export the data to keep for posterity and to use to verify the migration to JIRA.

### Acceptance Criteria ### 

Using the API endpoints provided by ZenHub [here](https://developers.zenhub.com/), please ensure the export includes at _least:_
- [x] Repo 
- [x] Issue type
- [x] **Issue number**
- [x] Issue title
- [x] **Pipeline**
- [x] Issue text
- [x] Labels
- [x] Assignee
- [x] Sprint
- [x] **Estimate**
- [x] **Epic**
- [ ] Milestone
- [x] Comments

Ideally, please package into a spreadsheet for ease of use. Save both JSON and spreadsheet conversion and load to Google Drive (add link to ticket).

**Comment by sasha-dresden** [comment]
Ok, got all the data compiled. Attached is both the json I built from 3 separate queries in order to grab all the data, as well as 2 versions of an excel file. One has arrays split into separate columns (so for example if there are 5 comments, each would be in a separate column, like comment_1, comment_2, etc) and a second one with all arrays smooshed into a single column separated by a pipe. (so for example if there were 2 blocking issues on a particular issue, there would be a single "blocking issues" column and for that row, the the "blocking_issues" field would say something like: 1063: title | 1064: title)

[issue-data.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2ZnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68841feead4f75967e9fad6dd47eee54499103fe/issue-data.zip)

Oh one thing to note, I could not retrieve milestone data for issues, well, I mean I could, but there was none. Everything came back null, which is why I didn't check it. I double checked and I believe while we have a few milestones created in github, we haven't actually assigned any issues to any of them.

**Comment by sasha-dresden** [comment]
@AureliaKhorsand here is the export of issues from Github, both in json and excel format. The excel file here is much easier to read as I was not dealing with blocking/blocked issues and for the comments, I left it with just the comment count and the comment url, so if you want the full comments, just follow the url link, but if you want it similar to how I did comments in one of the zenhub versions, I could do that as well with a little bit of data merging.

[github-data.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1hoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c48b5b6cc09f7595e6dcd35b7ffe5554bd7238d3/github-data.zip)

**Comment by AureliaKhorsand** [comment]
@MitchellTCG @sasha-dresden I would say that this ticket is complete as far as I'm concerned, and the work we are doing is now tracked in project-management #88. Sasha, was this a 5-pointer?

**Comment by AureliaKhorsand** [comment]
@MitchellTCG no QA review needed,  not a functional ticket. We got the data we needed both from ZenHub and from GitHub.

**Comment by WiseQA** [comment]
@MitchellTCG didn't see milestone checked on of list in AC.

Per BA's no QA review needed on this ticket, as no functionality in this ticket to test against FECFile.

Moved to Stage Ready.
